local LORE = {
  "The Emperor of Mankind sits upon the Golden Throne, an undying carcass powered by a thousand psychic sacrifices daily, serving as the Imperium's literal and spiritual battery.",
  "Space Marines, or Adeptus Astartes, are bio-engineered super-soldiers, organized into Chapters of roughly a thousand warriors, each sworn to protect the Emperor.",
  "The Imperial Guard, now the Astra Militarum, is the Imperium's primary fighting force, composed of trillions of regular human soldiers levied from countless worlds.",
  "Inquisitors are the Emperor's secret police, wielding near-absolute power to root out heresy, corruption, and the alien threat across the galaxy.",
  "The Adeptus Mechanicus are the machine-worshippers of Mars, who maintain the Imperium's technology and believe all knowledge is contained in the Omnissiah.",
  "The Ecclesiarchy, or the Adeptus Ministorum, is the official state church, spreading the Imperial Creed that venerates the Emperor as a god.",
  "The Administratum is the unimaginably vast bureaucracy of the Imperium, notorious for its inefficiency and endless mountains of parchment.",
  "Hive Worlds are colossal, densely populated planets where billions of humans live in stratified, mile-high cities, never seeing the natural sun.",
  "Navigators are sanctioned mutants with a third eye that allows them to perceive the currents of the Warp, making interstellar travel possible.",
  "The Astropathic Choir is a massive network of psychers who mentally scream across light-years to transmit messages, often driving them insane.",
  "Bolters are the standard armament of a Space Marine, firing mass-reactive explosive shells that shred unarmored foes.",
  "The High Lords of Terra are the twelve unelected officials who rule the Imperium in the Emperor's name, often locked in centuries-long power struggles.",
  "Venerable Dreadnoughts are once-mortally-wounded heroes encased in sarcophagi within powerful war machines, kept alive for centuries to continue fighting.",
  "An Exterminatus is the complete destruction of a planet's biosphere or population, a drastic measure used to prevent the spread of irreparable corruption or contagion.",
  "The Black Templars maintain that the Codex Astartes is merely a suggestion, and they wage eternal crusades with no home-world, seeking battle across the stars.",
  "Chaos is the corrupting influence of the Warp, born from the sentient emotions of mortals and manifested through the four great Chaos Gods.",
  "Khorne, the Blood God, embodies violence, murder, and rage, caring only from the spilling of blood, regardless of whose.",
  "Tzeentch, the Changer of Ways, is the master of ambition, conspiracy, and evolution, whose plans are infinitely complex and often contradictory.",
  "Nurgle, the Plague Lord, is the god of entropy, disease, and despair, who offers his followers a perverse form of morbid contentment.",
  "Slaanesh, the Dark Prince, is the god of excess, pleasure, and obsession, born from the psychic culmination of the ancient Eldar empire's depravity.",
  "Chaos Space Marines are the Traitor Legions and their descendants, who turned against the Emperor during the Horus Heresy ten millennia ago.",
  "The Eye of Terror is a massive, permanent Warp rift in space, serving as the corrupted home-base for the largest concentrations of Chaos forces.",
  "A Daemon is a psychic entity and manifestation of a Chaos God, a being of pure Warp-stuff that can possess mortal bodies.",
  "Warbands of Chaos Space Marines constantly launch Black Crusades into Imperial territory, seeking plunder, power, or simply to spread carnage.",
  "Possessed Marines have willingly allowed a Daemon to merge with their bodies, gaining horrific mutations and great power at the cost of their sanity.",
  "Fabius Bile, the Clonelord, is a mad scientist of the Chaos Space Marines who creates monstrous Astartes variants and clones the Primarchs for his dark experiments.",
  "The Iron Warriors specialize in siege warfare, preferring to grind their enemies down with overwhelming artillery and fortifications.",
  "Word Bearers are the first and most zealous of the Traitor Legions, viewing the Chaos Gods as true deities to be worshipped and obeyed.",
  "Daemon Worlds are planets so utterly warped by Chaos that the natural laws of reality break down, forming living, mutable hellscapes.",
  "The Great Rift, a massive warp storm, tore the galaxy in half and plunged the Imperium Nihilus into an age of perpetual darkness and terror.",
  "The Orks are a vast, green-skinned, fungal species whose very existence and technology are governed by a psychic field called WAAAGH!, which makes things work simply because they believe they will.",
  "An Ork Warlord will eventually attract enough other Orks to form a massive WAAAGH!, a migratory crusade of destruction that consumes solar systems.",
  "The Orks' simple mentality means they find fighting to be the greatest pleasure, and they see constant warfare as a joyous form of existence.",
  "The Eldar, or Aeldari, are a dwindling, ancient race, once masters of the galaxy, whose hubris birthed Slaanesh and led to the near-total destruction of their civilization.",
  "Craftworlds are colossal, sentient, space-faring vessels that house the surviving Eldar, travelling the galaxy on carefully calculated courses to avoid detection.",
  "Farseers are the most powerful Eldar psykers, who use complex divinations to navigate the future and guide their people along the Path of the Seer.",
  "The Dark Eldar, or Drukhari, are depraved corsairs from the dark city of Commorragh who stave off the slow psychic draining of Slaanesh by inflicting pain on others.",
  "The Tyranids are an extragalactic super-organism, a terrifying swarm driven by the collective Hive Mind with the sole purpose of consuming all biomass in the galaxy.",
  "The Shadow in the Warp is the psychic pall cast by the Hive Fleet that dampens and eventually cuts off all psychic communication and activity, including the Astronomican.",
  "A Genestealer Cult is a clandestine, multi-generational xenos infestation that secretly takes root on Imperial worlds, preparing the populace for the arrival of the main Tyranid fleet.",
  "The T'au Empire is a young, rapidly expanding civilization driven by the concept of the Greater Good, utilizing advanced technology and coordinated combined arms warfare.",
  "The T'au rely heavily on their robotic Battlesuits, such as the agile Crisis Suits and the towering Riptides, for heavy combat.",
  "The Necrons are a race of ancient, skeletal robotic warriors who willingly transferred their consciousness into living metal bodies, a process that cost them their souls.",
  "Tomb Worlds are Necron planets where the entire population lies in silent stasis, waiting for a signal to awaken and reclaim their former galactic empire.",
  "C'tan, or Star Gods, are powerful entities of pure energy who were tricked by the Necrons into becoming bound to their living metal bodies.",
  "The Ork's ability to collectively believe things makes them incredibly dangerous: a red vehicle is factually faster simply because every Ork believes it is.",
  "The Jokaero are mysterious, diminutive alien orangutans whose incredible, instinctively created technology is beyond the understanding of the Mechanicus.",
  "The Kroot are a mercenary avian species who integrate the DNA of their defeated enemies by eating them, gaining their best genetic traits.",
  "The Hrud are a reclusive, nomadic xenos species whose passage can instantly and violently age their surroundings, causing rust, decay, and rapid biological senescence.",
  "The Interex was a technologically sophisticated, harmonious human and xenos alliance that was tragically destroyed during the Great Crusade due to misunderstanding and manipulation.",
  "The Great Crusade was the Emperor's 200-year-long war to reunite the scattered human worlds under the banner of the Imperium before the Horus Heresy.",
  "The Horus Heresy was a devastating galaxy-wide civil war where half of the Primarchs and their Space Marine Legions betrayed the Emperor to serve Chaos.",
  "The Primarchs were the twenty superhuman sons of the Emperor, each a master strategist and warrior, who led the original Space Marine Legions.",
  "Horus Lupercal, the Emperor's favored son and Warmaster of the Great Crusade, was the first and greatest Primarch to fall to Chaos.",
  "The Siege of Terra was the climactic battle where the Emperor finally defeated the corrupted Horus, but was mortally wounded and interred on the Golden Throne.",
  "The Burning of Prospero was the Imperial punitive action that led the psychic Thousand Sons Legion, led by Magnus the Red, into the arms of Tzeentch.",
  "The Iron Cage was the brutal, protracted siege orchestrated by Perturabo, Primarch of the Iron Warriors, as a decades-long trap to utterly break the Imperial Fists.",
  "The War in the Webway was a secret, disastrous conflict fought by the Emperor and his Custodes to carve a stable path through the dimension between the stars.",
  "The Great Scouring was the ruthless campaign of revenge and reunification waged by the loyalist Primarchs after the Heresy to cleanse the galaxy of the remaining traitors.",
  "The Codex Astartes, penned by Roboute Guilliman, decreed that the Legions be broken into smaller, more manageable Chapters to prevent future rebellions.",
  "The Age of Apostasy saw the tyrannical rule of Goge Vandire, whose cruelty was eventually ended by the forces of the Adepta Sororitas and the Imperial Guard.",
  "Abaddon the Despoiler, the Warmaster of Chaos, led twelve failed Black Crusades before the thirteenth succeeded in cracking the Imperium.",
  "The Fall of Cadia saw the destruction of the fortress world and the subsequent creation of the Great Rift, marking a turning point in galactic history.",
  "Guilliman was resurrected in the current millennium, taking the title of Lord Commander of the Imperium and instigating the Indomitus Crusade.",
  "The Beast Arises was a massive conflict against a colossal Ork WAAAGH! that shattered entire Imperial institutions and almost toppled the Imperium.",
  "The Custodes, or the Adeptus Custodes, are the Emperor's personal guard, genetically superior even to the Space Marines and clad in golden armor.",
  "The Sisters of Battle, or the Adepta Sororitas, are the all-female military arm of the Ecclesiarchy, burning heretics with righteous zeal and flamer fire.",
  "The Deathwatch is a secret, specialized Chapter composed of Space Marine veterans from across all Chapters, tasked with eliminating specific xenos threats.",
  "The Grey Knights are a mysterious, secret Chapter of Space Marines composed entirely of powerful psykers, dedicated to fighting the daemonic forces of Chaos.",
  "The Sisters of Silence are a legion of anti-psykers whose mere presence nullifies psychic powers, a rare and vital defense against the Warp.",
  "Rogue Traders are Imperial agents given Letters of Marque, granting them the right to explore and exploit the unknown regions of the galaxy for the Emperor.",
  "The Adeptus Arbites are the militarized law enforcement of the Imperium, responsible for upholding the Lex Imperialis, or Imperial law, on human worlds.",
  "Tech-Priests of the Mechanicus see all technology as sacred and perform extensive surgical and mechanical modifications to themselves in search of mechanical perfection.",
  "The Librarius is the division of a Space Marine Chapter that houses its sanctioned psykers, who channel the power of the Warp to aid their brethren.",
  "Commissars are political officers within the Astra Militarum who ensure the absolute loyalty and morale of the troops, often by summary execution for cowardice.",
  "The Warp, or Immaterium, is a parallel dimension of raw psychic energy, the source of all magic, faster-than-light travel, and daemonic entities.",
  "The Astronomican is a psychic beacon generated by the Emperor, allowing human ships to navigate the tumultuous Warp across the galactic core.",
  "Warp Travel is accomplished by plunging a ship into the Immaterium, where the journey is instantaneous but perilous, subject to daemonic attack and temporal anomalies.",
  "Heresy is the ultimate crime in the Imperium, ranging from worshiping false gods to consorting with aliens or even doubting the Emperor.",
  "Mutants are often shunned and persecuted in the Imperium, though some sanctioned variants, like the Navigators and some Astropaths, are grudgingly accepted.",
  "The Golden Age of Technology was a period millennia ago when humanity achieved a technological peak, before a widespread revolt of sentient machines.",
  "Stasis fields are ancient technological remnants used to indefinitely freeze objects or people in time, sometimes over thousands of years.",
  "A Relic in the Imperium is often a centuries-old piece of equipment, maintained with obsessive, near-religious fervor by the Mechanicus.",
  "Archaeotech refers to technology recovered from the Golden Age, often so advanced that the Mechanicus cannot replicate or fully understand it.",
  "The standard state of the galaxy is one of Total War, where the Imperium is constantly fighting on thousands of fronts against countless enemies.",
  "The Slaughter is the ultimate goal of the World Eaters, the Chaos Space Marines of Khorne, whose only purpose is an endless, bloody rampage.",
  "The Fallen are the rogue, non-Chaos loyalist members of the Dark Angels Legion who were separated by a Warp storm during the Heresy.",
  "The Harlequins are mysterious, theatrical Eldar followers of the Laughing God, Cegorach, who dance between the realms of the living and the dead.",
  "Ambulls are massive, subterranean, burrowing xenos creatures often utilized as heavy labor or combatants on frontier worlds.",
  "The Lizardmen from the fantasy world are hinted to be a related species to the Slann, ancient, powerful psychic toad-like beings who may have shaped the galaxy.",
  "The Squats, or Leagues of Votann, were a distinct, technologically advanced human subspecies who were believed to be consumed by the Tyranids, but have recently returned.",
  "The Yu'vath were an ancient, horrifying species that created the sinister, flesh-warping artifacts of the Dark Mechanicus.",
  "The Q'orl are a race of insectoid beekeepers who build incredible structures from wax and honey, who fought the Imperium during the Sabbat Worlds Crusade.",
  "The Lesser Daemon of the Plague God Nurgle, a Nurgling, is a diminutive, giggling miniature of its patron deity, spreading joy and disease.",
  "The Gretchin, or Grots, are the subservient, cowardly, but often surprisingly ingenious smaller cousins of the Orks, used as expendable labor and cannon fodder.",
  "For one moment, on the world of Sanctuary 101, a single, ordinary Guardsman successfully killed a Daemon Prince of Chaos with a well-placed grenade.",
  "The Great Work is the name given to the Emperor's failed project to create a safe, stable passage into the Webway for humanity, bypassing the Warp.",
  "The Planet of the Sorcerers is the Thousand Sons' home world within the Eye of Terror, a temporal paradox where time flows inconsistently.",
  "Despite all the terror, the vast majority of human life in the Imperium is a repetitive, soul-crushing toil, with every individual completely insignificant to the grand, galactic conflict.",
  "The Slaugth are horrific, maggot-men xenos who infiltrate human society to feast on the dead and decay.",
  "The two Lost Primarchs were excised from all Imperial records following an unknown tragedy and are now only mentioned in cryptic, fear-laden whispers.",
  "Lion El'Jonson, Primarch of the Dark Angels, has recently returned from a 10,000-year slumber, now awake and leading his confused Chapter into a new age.",
  "Leman Russ, the Wolf Lord, left the Imperium seeking a cure for the Emperor's injuries, vowing to return for the Final Battle at the End Times.",
  "Corvus Corax, the shadowy Primarch of the Raven Guard, was so horrified by the Horus Heresy that he entered the Eye of Terror to pursue and execute his traitorous brothers.",
  "Vulkan, the compassionate Primarch of the Salamanders, is an Perpetual, meaning he can regenerate from even the most grievous and fatal wounds.",
  "Jaghatai Khan, the master of hit-and-run warfare for the White Scars, vanished chasing Dark Eldar deep into the labyrinthine Webway.",
  "Ferrus Manus, the Gorgon of the Iron Hands, had hands sheathed in self-replicating liquid metal that he regarded as tools, not limbs.",
  "Sanguinius, the winged Primarch of the Blood Angels, died fighting Horus above Terra, forever crippling the forces of Chaos.",
  "Rogal Dorn, the stalwart Primarch of the Imperial Fists, was believed slain in the wreckage of a Chaos cruiser, though his hand was the only recovered remnant.",
  "Perturabo ascended to Daemonhood after sacrificing the gene-seed of over four hundred Imperial Fists following the Iron Cage incident.",
  "Konrad Curze, the prophetic Night Haunter, foresaw his own death and allowed an Imperial assassin to kill him, seeing it as the only just outcome of his life.",
  "Angron, the Primarch of the World Eaters, was forced into gladiator servitude on his homeworld, where he was implanted with the savage Butcher's Nails.",
  "Fulgrim, Primarch of the Emperor's Children, personally slew his brother Ferrus Manus and offered his head to Slaanesh.",
  "Mortarion, the Death Lord, rebelled due to his hatred of psychic powers and has since become the bloated, plague-ridden Daemon Primarch of the Death Guard.",
  "The Thunder Warriors were the Emperor's proto-Astartes, purged by the Custodes and the first Space Marines at the dawn of the Imperium.",
  "The Primarch Project was secretly overseen by the Emperor and the Mechanicum's most brilliant minds deep beneath the Himalayans on Terra.",
  "Each loyalist Primarch had a unique relationship with the Emperor, ranging from Dorn's unflinching obedience to Leman Russ's playful belligerence.",
  "The Emperor originally intended for the Primarchs to lead humanity into a new age of science, not endless religious warfare.",
  "The infant Primarchs were scattered across the galaxy by the machinations of the Chaos Gods, each landing on a unique world that shaped his destiny.",
  "The Custodes' primary task is the silent, unending vigil over the decaying body of the Emperor on the Golden Throne.",
  "The Terran Unification Wars were a brutal series of conflicts waged by the Emperor to bring the disparate, techno-barbaric clans of Old Terra under his rule.",
  "The Emperor’s psychic might is so vast that his dreams and thoughts occasionally manifest as minor, fleeting Warp entities.",
  "Malcador the Sigillite was the Emperor’s most trusted human confidante, who sat upon the Golden Throne in the Emperor’s stead during the final battle with Horus.",
  "The Eversor Assassin is genetically modified and chemically augmented to be a berserk killing machine, intended to die shortly after completing its mission.",
  "The Vindicare Assassin is the ultimate Imperial sniper, capable of eliminating targets from miles away in complete silence.",
  "The Callidus Assassin uses an advanced polymorphine drug to flawlessly impersonate any human being, infiltrating deep into enemy institutions.",
  "The Culexus Assassin is a living psychic blank, an anti-psyker who is often perceived by normal humans as an unsettling gap in their senses.",
  "The Primaris Marines are a new, larger, and genetically enhanced generation of Space Marines created in secret by Archmagos Cawl during the Heresy.",
  "The Rubric of Ahriman was a disastrous spell cast by the Thousand Sons Sorcerer that turned all non-psyker members of the Legion into mindless, animated dust within their armor.",
  "Daemonic Incursions are battles where the veil between the Warp and reality tears, allowing the legions of Chaos to temporarily pour onto a mortal world.",
  "The Lost and the Damned is the collective name for the colossal, disorganized hordes of human cultists, mutants, and renegades who fight alongside Chaos Space Marines.",
  "A Chaos Cult often begins with a single, charismatic heretic or a subtle psychic corruption, growing in secret until it explodes in open rebellion.",
  "The Obliterators are Chaos Marines whose bodies have been horribly infected by a techno-organic plague that allows them to manifest any weapon they can imagine.",
  "The Decimator is a massive Chaos war engine piloted by a Daemon who delights in causing endless torment and confusion on the battlefield.",
  "The Daemon Engines are the twisted, mechanized horrors of Chaos, where a Warp entity has been brutally bound to a war machine's chassis.",
  "The Emperor's Children dedicate themselves to artistic excess, horrific sensory experiences, and inflicting unimaginable suffering in the name of Slaanesh.",
  "The Death Guard are eternally slow, inexorable, and immune to pain and injury, advancing under massive swarms of flies and spreading Nurgle's infections.",
  "The World Eaters are dominated by the Butcher's Nails, a psycho-surgical implant that causes a constant, agonizing thirst for extreme violence.",
  "The Night Lords use terror and psychological warfare, flaying victims alive and broadcasting their screams to break the morale of their enemies.",
  "Iron Warriors often use human slaves as live targets or as organic components in their massive, grim siege machinery.",
  "Dark Apostles are the zealous priests and spiritual leaders of the Word Bearers, dedicated to turning entire planetary populations to Chaos worship.",
  "The Legion of the Damned are mysterious, ghostly figures in black, flaming power armor who appear only in the direst moment of need to aid Imperial forces before vanishing.",
  "The Helbrute is the Chaos equivalent of a Dreadnought, often containing a raving, insane marine locked inside a sarcophagus consumed by rage and mutation.",
  "Terminators in Chaos Legions are known as Chaos Terminators, often clad in archaic, highly-mutated versions of their Heresy-era armor.",
  "The Scream of Tzeentch is the collective, insane babbling of all the entities within the Great Schemer's realm, a sound that can shatter a mortal mind.",
  "The Great Game is the eternal, destructive rivalry between the four Chaos Gods, whose shifting alliances and backstabbing affect all reality.",
  "Chaos Spawns are once-mortal beings who have been overloaded with mutation and Warp power, reducing them to slobbering, unpredictable monsters.",
  "Lesser Daemons include Khorne's savage Bloodletters, Tzeentch's giggling Horrors, Nurgle's merry Plaguebearers, and Slaanesh's graceful Daemonettes.",
  "Vigilus is a key planet near the Great Rift that is currently a pivotal, multi-sided warzone between several Imperial, Chaos, and Xenos factions.",
  "The Black Legion is composed of remnants and marines from all the Traitor Legions, united in their hatred of the Imperium.",
  "Daemon Weapons are horrific arms that have a Daemon painfully bound inside them, lending them incredible power but often trying to control the wielder.",
  "The Traitor Guard are regiments of the Astra Militarum who have sworn allegiance to the Chaos Gods, often possessing crude mutations and fanatical zeal.",
  "The Flesh Tearers are a successor Chapter of the Blood Angels constantly on the verge of succumbing to the bloodthirsty psychic curse known as the Black Rage.",
  "The Red Corsairs are a powerful warband of Chaos renegades, once Astral Claws, who dominate the infamous pirate haven known as the Maelstrom.",
  "The Dark Mechanicum are Tech-Priests who worship Chaos, specializing in creating horrifying, bio-fused weaponry and Daemon Engines.",
  "The Iron Warriors frequently employ terrifying Obliterators as their shock troops to breach the strongest fortifications.",
  "The Plague Marines of the Death Guard are so resilient due to Nurgle's \"blessings\" that they often continue fighting with horrific injuries that would kill a normal marine.",
  "Possession is often the eventual fate of powerful Chaos Sorcerers whose bodies can no longer contain the sheer power of the Warp they channel.",
  "The Soul Grinder is a massive, multi-legged Daemon Engine that was once a Lesser Daemon who failed its god and was forced into a mechanized body.",
  "Tyranids adapt so rapidly that a fleet invading a new galaxy often encounters defenses that are wholly ineffective against the next wave.",
  "Rippers are the smallest Tyranid organisms, overwhelming prey with sheer numbers and stripping bodies clean of biomass.",
  "The Genestealers' Kiss is the process by which a Genestealer infects a host, implanting its genetic material and making the victim subservient to the cult.",
  "The Patriarch is the founder of a Genestealer Cult, a massive, powerful Genestealer who serves as the focus of the cult's psychic mind.",
  "The Broodlord is a highly evolved, physically imposing Genestealer that leads the vanguard of a Genestealer Cult in battle.",
  "The Aeldari rely on Aspect Warriors, specialized soldiers who dedicate their entire lives to a single martial path, such as the swooping Swooping Hawks.",
  "Wraithbone is the psychic, solidified substance that forms the basis of all Eldar technology, which can be shaped by their mind.",
  "The Spirit Stones worn by the Eldar contain their souls, protecting them from the immediate, hungry grasp of Slaanesh upon death.",
  "The Ynnari are a relatively new faction of Eldar who worship Yvraine, the prophet of the nascent death god Ynnead, hoping to defeat Slaanesh.",
  "The Striking Scorpions are Eldar Aspect Warriors who excel at close-quarters combat, equipped with the chain-bladed Scorpion Chainsword.",
  "The Dark Reapers are heavy weapons Aspect Warriors who use terrifying missile launchers to inflict massive damage from afar.",
  "Wytches are the gladiatorial combatants of the Dark Eldar, who fight in bloody arenas in Commorragh and derive life-extending pleasure from their acts.",
  "Kabalites are the primary, merciless raiders and soldiers of the Dark Eldar who lead the slave raids into real space.",
  "The Incubi are the elite, disciplined warriors of the Dark Eldar, known for their perfect combat mastery and terrifying strength.",
  "The Archon is the supremely ruthless leader of a Dark Eldar Kabal, who maintains power through constant murder, intrigue, and displays of cruelty.",
  "The T’au Fire Caste are the primary soldiers and combat specialists, known for their proficiency with railguns and pulse weaponry.",
  "The Ethereals are the philosophical and political leaders of the T'au, whose presence instills unwavering loyalty and devotion to the Greater Good.",
  "Vespid Stingwings are xenos auxiliaries of the T’au, noted for their airborne combat and specialized energy weapons.",
  "Kroot Shapers are the leaders of their kind, who strategically choose which enemies the Kroot should consume to best adapt their genetics.",
  "Railguns are the devastating primary weapon of the T'au, capable of punching through the thickest armor with massive kinetic force.",
  "Necron Overlords are the most senior and powerful Necrons, obsessed with regaining their ancient glory and enslaving the other races.",
  "Necron Warriors are the basic foot soldiers, mindless robots who march in lockstep and self-repair thanks to their Reanimation Protocols.",
  "The Tomb Stalker is a terrifying, massive Necron construct that tunnels beneath the surface to ambush foes with multiple legs and death rays.",
  "Flayed Ones are Necrons consumed by a horrific mental disease that drives them to flay their foes and wear the skin as trophies.",
  "The Triarch Praetorians are the self-appointed guardians of Necron dynastic traditions, who often operate outside the direct control of any Overlord.",
  "Gauss Flayers are the standard weapons of Necron infantry, disintegrating targets on a molecular level.",
  "The Stompa is an Ork's massive, lumbering walking war machine, often armed with grossly oversized and unreliable weaponry.",
  "Burna Boyz are Orks obsessed with fire, wielding massive flame throwers that accidentally engulf both enemy and friend alike.",
  "An Ork Weirdboy is a volatile Ork Psyker who channels the collective WAAAGH! energy, often resulting in massive, uncontrolled psychic discharges.",
  "Ghazghkull Mag Uruk Thraka is the most powerful Ork Warlord, believed to be the prophet of the Ork gods, Gork and Mork.",
  "Flash Gitz are the showy, wealthy Orks of the Freebooter variety, armed with the biggest, shiniest, and most dangerous guns.",
  "The Snotlings are the smallest and weakest Orkoids, primarily used by Orks as pets, target practice, or highly expendable ammunition.",
  "Ork Mekboyz are the mad scientists who maintain and invent all the ramshackle, yet functional, Ork technology.",
  "The Squigs are various forms of low-intelligence Orkoid fauna used for everything from food to attack animals and even crude musical instruments.",
  "The Old Ones were a powerful, ancient psychic species who engineered the Eldar and Orks, and fought the Necrons and C'tan in a terrible galactic war.",
  "The Enslavers are terrifying Warp entities that specialize in possessing and manipulating large numbers of mortal psychers, spreading like a psychic virus.",
  "The Slann were the chief servants of the Old Ones, powerful psychers who were responsible for the creation and uplifting of several species.",
  "Psychic Awakening is a period of massive psychic phenomena across the galaxy, which led to the creation of the Great Rift.",
  "The Zoanthropes are specialized Tyranid creatures who serve as the Hive Mind's primary psychic artillery on the battlefield.",
  "The Spirit Host is a massive swarm of psychic remnants released upon the death of a powerful Eldar, often leading to a violent, temporary Warp surge.",
  "The Khrave are mind-eating xenos that plagued the galaxy during the Great Crusade, requiring the Lion to exterminate them.",
  "The Fra'al are a predatory avian species, often hired as mercenaries by the Dark Eldar for their swift, airborne strikes.",
  "The Loxatl are reptilian Xenos used by Chaos forces, specializing in guerrilla warfare and wielding primitive, yet potent, plasma weapons.",
  "Rak'Gol are brutal, cybernetic-enhanced raiders who terrorize the fringes of the galaxy and possess a disturbing mastery of flesh-metal surgery.",
  "The Demiurg are a stout, asteroid-dwelling Xenos race known for their unparalleled skills in deep-space mining and engineering.",
  "The Nicassar are a peaceful, bear-like Xenos species with powerful telekinetic abilities, acting as merchant partners for the T'au Empire.",
  "The Laer were an ancient, serpent-like species who possessed a sacred artifact that corrupted the Primarch Fulgrim to the worship of Slaanesh.",
  "The Thyrrus were a highly mobile, nomadic Xenos species known for their use of sound-based weaponry, now mostly destroyed by the Imperium.",
  "The Umbra are shadowy, parasitic beings of pure darkness who inhabit the deepest voids of space and prey on the life force of passing ships.",
  "The Sslyth are massive, serpentine Xenos who serve as mercenaries and bodyguards, often employed by the wealthiest Dark Eldar Archons.",
  "The Grox are massive, domesticated reptilian creatures, widely farmed across the Imperium for their tough, nutritious meat.",
  "The Catachan Jungle Fighters are among the most fearsome Astra Militarum regiments, raised on a death world famous for its monstrous flora and fauna.",
  "The Death Korp of Krieg are grim, suicidal Guardsmen who seek atonement through constant, self-sacrificial warfare.",
  "The Vostroyan Firstborn are an aristocratic, proud Astra Militarum regiment known for their ornate uniforms and heirloom weaponry.",
  "The Valhallan Ice Warriors are stoic and tough Guardsmen who specialize in armored and infantry combat on frozen, hostile worlds.",
  "The Attilan Rough Riders are mounted Guardsmen who charge into battle on genetically engineered horses, utilizing explosive lances.",
  "The Ogryns are genetically stable human abhumans, large and strong but dim-witted, often employed as shock troops in the Astra Militarum.",
  "Ratlings are small, sneaky abhumans with an innate talent for cooking and marksmanship, frequently used as snipers and field cooks.",
  "The Navis Nobilis is the powerful, politically entrenched guild that supplies the Imperium with its essential Navigators.",
  "The Black Ships are sinister vessels that constantly patrol the galaxy, rounding up nascent psykers to either be trained or sacrificed on Terra.",
  "The Mechanicus' primary chant is the Litany of the Machine, a ritualistic hymn sung to pacify the Machine Spirit before activation.",
  "The Machine Spirit is the concept that every piece of technology, from a lasgun to a Titan, possesses a rudimentary, volatile form of consciousness.",
  "The Cult Mechanicus is obsessed with recovering and understanding Standard Template Constructs (STCs), blueprints for lost Golden Age technology.",
  "The Titan Legions, or Adeptus Titanicus, are the colossal war engines of the Mechanicus, controlled by a crew physically wired into the machine.",
  "The Skitarii are the cybernetic foot soldiers of the Mechanicus, their flesh willingly replaced with augmentations to serve the Omnissiah.",
  "An Archmagos is the highest rank within the priesthood of the Mechanicus, ruling the Forge Worlds and directing titanic scientific undertakings.",
  "The Lexellentia is the vast, complex, and often contradictory legal code that governs the interactions between the Imperium and the Mechanicus.",
  "Forge Worlds are planets entirely dedicated to manufacturing and industry, often smothered in pollution and covered in endless factories.",
  "The Holy Trinity of the Mechanicus is the belief in the Omnissiah, the Machine God, and the Motive Force that drives all existence.",
  "The Mechanicus often views innovation as Heresy, believing that all true knowledge was already discovered during the Golden Age.",
  "A Tech-Priest’s true name is a complex series of binary code, often too long for a human to pronounce or comprehend.",
  "Servitors are lobotomized humans whose bodies are permanently melded with mechanical components to perform simple, repetitive tasks.",
  "The Ordo Reductor is the division of the Mechanicus that specializes in designing and building siege engines and destructive weaponry.",
  "The Secutarii are the highly specialized, aggressive vanguard forces of a Skitarii army, often armed with lightning-arc weaponry.",
  "Plasma weapons are notoriously temperamental, prone to dangerous overheating and even explosive meltdown if improperly maintained or overcharged.",
  "The Mechanicus believes that the Emperor is the physical manifestation of the Omnissiah on the mortal plane.",
  "The Iron Men were the sentient, universally rebellious machine-intelligence race that led to the devastating downfall of the Golden Age of Technology.",
  "The Mechanicus maintains a vast, hidden library on Mars that contains ancient secrets and forbidden knowledge, locked away for millennia.",
  "Knights are smaller, one-person mechanized walkers, piloted by nobles from Knight Worlds who owe a feudal allegiance to the Mechanicus or the Imperium.",
  "Binaric Cant is the digital language of the Tech-Priests, often sounding like static and clicks to the untrained ear.",
  "The Adeptus Astra Telepathica is the organization responsible for training and managing the Imperium's Astropaths and Sanctioned Psykers.",
  "The Schola Progenium are the high Imperial orphanages that train the children of deceased Imperial officials and heroes, often producing Commissars and Sisters of Battle.",
  "Terra's surface is no longer a natural world, but a colossal, multi-layered megacity, built upon the ruins of countless older civilizations.",
  "The Great Foundries on Mars are so vast that their operations often cause earthquakes and weather manipulation on a global scale.",
  "The Lexicanum is the immense, constantly updating, and often contradictory historical archive of the Imperium.",
  "Cybernetic Augmentation is a religious rite for the Mechanicus, shedding weak flesh for the strength of the machine.",
  "A Tech-Adept is a junior rank in the Mechanicus, learning the endless rituals and maintenance prayers required for common machinery.",
  "The Noosphere is a highly secretive, encrypted network used by the Mechanicus to communicate digitally and upload data instantly.",
  "The Cult of the Dragon is a splinter faction of the Mechanicus that believes the Omnissiah is a giant, metallic, warp-eating dragon trapped beneath Mars.",
  "Macro-clades are the massive, regiment-sized deployments of Skitarii forces led by a high-ranking Tech-Priest.",
  "The Munitorum is the branch of the Administratum responsible for supplying the Astra Militarum, a task of staggering, often-failed logistical complexity.",
  "The Laspistol is the smallest and most common las-weapon, often used by officers, guardsmen, and low-level Imperial officials.",
  "Basilisks are the terrifying, long-range self-propelled artillery pieces of the Astra Militarum, capable of hitting targets hundreds of miles away.",
  "The Leman Russ Battle Tank is the rugged, ubiquitous main battle tank of the Imperial Guard, often found in countless regional variants.",
  "The Sentinel is a light, agile scout walker used for reconnaissance, often equipped with multi-lasers or heavy flamers.",
  "Hotshot Lasguns are high-powered las-weapons carried by the elite Tempestus Scions, requiring a special backpack-mounted power pack.",
  "Mordian Iron Guard regiments are known for their rigid discipline, perfectly synchronized drills, and distinctive, parade-ground uniforms.",
  "The Elysian Drop Troops are highly specialized, airborne regiments who deploy from orbit and fight mainly behind enemy lines.",
  "A Regimental Standard is a sacred banner carried into battle, believed to focus the morale of the entire unit and ward off misfortune.",
  "Penal Legions are regiments composed entirely of criminals and disgraced soldiers, used as expendable human wave attacks on the most dangerous fronts.",
  "Lord Solar Macharius was the greatest Imperial Commander since the Primarchs, leading a century-long, successful crusade across a third of the galaxy.",
  "The Emperor Protects is the most common phrase and reassurance used by the citizens and soldiers of the Imperium.",
  "The Creed of the Machine God is a complex set of tenets and rituals that the Mechanicus adhere to with fanatic devotion.",
  "The Grox Rider is a surprisingly effective, if notoriously smelly, form of cavalry employed by some less technologically advanced Guardsman regiments.",
  "The Storm Troopers, now Tempestus Scions, are the highly trained, better-equipped special forces of the Astra Militarum.",
  "Trench Warfare remains a common, brutal reality for the Imperial Guard, especially on worlds subject to protracted sieges.",
  "A Planet Kill is a term for a strategically worthless planet where endless amounts of resources and manpower are pointlessly expended.",
  "The Fleet-based Chapters of the Space Marines, like the White Scars, have no homeworld and use their massive starships as their mobile fortresses.",
  "The Orbital Defense Stations that protect Imperial planets are often enormous, centuries-old structures equipped with continent-shattering weaponry.",
  "Gun Servitors are common defense assets, automated weapons platforms fused with a human brain to control the targeting systems.",
  "The Praetorian Guard were the elite, Terran-raised Guard regiments who fought alongside the Custodes during the Siege of Terra.",
  "The Sanctioned Psykers of the Imperial Guard are often shunned, viewed with suspicion, and kept far from the common troops due to their Warp vulnerability.",
  "Rosarius is a personal force field carried by high-ranking Imperial officers, providing a small but potent layer of protection against enemy fire.",
  "The Hellhound is a fast, tracked vehicle armed with a large, dedicated flamethrower, used for clearing bunkers and trenches.",
  "The Hydra Flak Tank is a specialized anti-aircraft vehicle used by the Astra Militarum to clear the skies of enemy flyers.",
  "The Valkyrie Assault Carrier is a reliable, heavily armed transport aircraft used by the Imperial Guard for rapid deployment and close air support.",
  "Plasma Guns are capable of incinerating most infantry in a single shot, but are dangerously unstable and can backfire spectacularly.",
  "The Heavy Bolter is a multi-barreled machine gun firing miniature explosive rockets, a favored suppressive weapon of the Imperium.",
  "A Glory Kill is a concept in the Astra Militarum where a soldier performs a selfless, heroic act that saves the regiment, even at the cost of their own life.",
  "The Abhuman Contingents are sometimes attached to Guard regiments, providing unique strengths like the strength of the Ogryn or the sight of the Ratling.",
  "Gene-Seed is the highly sacred, genetically encoded biological material used to transform a human boy into a Space Marine.",
  "The Imperial Fists are master builders and siege engineers, famous for their unwavering discipline and unbreakable defenses.",
  "The Blood Angels suffer from the Red Thirst, a constant, inherited psychic craving for blood that threatens to turn them into savage killers.",
  "The Ultramarines are the most strategically sound and well-organized Chapter, adhering strictly to the tactical doctrines of the Codex Astartes.",
  "The Dark Angels are burdened by the secret of the Fallen, which they hunt relentlessly across the galaxy, prioritizing this above all else.",
  "The Space Wolves, or Rout, reject the Codex Astartes, maintaining their tribal traditions, Great Companies, and unique Canis Helix mutations.",
  "The Raven Guard specialize in rapid deployment, sabotage, and sudden, precise strikes that decapitate the enemy command structure.",
  "The Salamanders are the most humanitarian of the Space Marine Chapters, often striving to protect innocent civilians during conflicts.",
  "The Iron Hands replace increasing amounts of their biological body with cybernetics, believing flesh is weak and that only the machine is reliable.",
  "Apothecaries are the Space Marine medics, whose primary duty is retrieving the Gene-Seed from a fallen battle-brother to preserve the Chapter's future.",
  "Techmarines are Space Marines trained on Mars, who maintain the Chapter's vehicles and weaponry while serving the Omnissiah.",
  "Librarians are the Space Marine Psykers, who wear blue armor and use their mental powers to assault the enemy and predict their movements.",
  "Chaplains are the spiritual leaders of a Space Marine Chapter, wearing black armor and bearing the skull-visaged Crozius Arcanum.",
  "Scouts are the initiates of a Space Marine Chapter, often operating behind enemy lines before receiving their full power armor.",
  "Terminator Armor is the heaviest, most protective suit of power armor, often deployed for teleport assaults into the most dangerous locations.",
  "The Assault Squads use Jump Packs to soar over the battlefield, specializing in shock and close-quarters chainsword combat.",
  "Sternguard Veterans are highly experienced Space Marines who specialize in tactical combat and the use of rare, powerful specialist weaponry.",
  "Vanguard Veterans are the elite, jump-pack equipped veterans of a Chapter, specializing in rapid, high-impact close-combat strikes.",
  "The Flesh is Weak is the central, often repeated mantra of the Iron Hands Chapter.",
  "Battle-Brothers is the term Space Marines use to refer to their Chapter mates, denoting their eternal, unbreakable bond.",
  "The Red Scorpions are an austere, highly formal Space Marine Chapter who have a deep distrust of Psykers and emphasize genetic purity.",
  "The Marines Malevolent are a callous, violent Chapter known for prioritizing their mission success over the protection of any civilians.",
  "The Carcharodons Astra are a shadowy, terrifying Chapter of unknown origin, rumored to be ex-Night Lords who cruise the galactic edge seeking battle.",
  "The Mantis Warriors were once sentenced to penitent crusade for defying Imperial authority during the tumultuous Badab War.",
  "The Relictors were declared Excommunicate Traitoris for attempting to use daemonic artifacts against the forces of Chaos.",
  "The Exorcists are a secretive Chapter who regularly undergo Daemonic possession rituals, developing a frightening immunity to Warp taint.",
  "The Novamarines are an Ultramarines successor Chapter famous for their strict adherence to the Codex and impeccable battlefield performance.",
  "Land Raiders are the heaviest, most heavily armored Space Marine transport vehicles, often equipped with twin-linked Lascannons.",
  "The Whirlwind is a long-range Space Marine artillery vehicle, firing barrages of high-explosive missiles to clear enemy concentrations.",
  "A Master of the Forge is the most senior Techmarine of a Chapter, responsible for maintaining its most sacred and complex equipment.",
  "Rhino transports are the ubiquitous, armored personnel carriers used by nearly all Astartes and Imperial forces.",
  "The First Founding refers to the original twenty Space Marine Legions that fought during the Great Crusade and the Horus Heresy.",
  "The Sub-sector Commander is the highest-ranking Space Marine officer in a specific geographical area, often reporting only to the Chapter Master.",
  "The Chapter Fortress-Monastery is the primary home base of a Space Marine Chapter, often a massive, heavily fortified structure.",
  "The Death Company are those Blood Angels afflicted by the overwhelming Black Rage, deployed in suicidal charges to find an honorable death.",
  "Primaris Intercessors are the new mainline battle-brothers of the Primaris Chapters, armed with the longer-ranged Bolt Rifle.",
  "Hellblasters are Primaris Marines armed entirely with powerful plasma incinerators, acting as dedicated anti-armor specialists.",
  "Reivers are Primaris Marines specializing in covert assault and shock tactics, often descending on grapple lines for close-quarters mayhem.",
  "Aggressors are massive, heavily armored Primaris Marines specializing in close-range, overwhelming fire support with flamestorm gauntlets.",
  "The Master of Sanctity is the overall title for the chief Chaplain of a Space Marine Chapter, the keeper of its spiritual purity.",
  "The Inquisition is divided into three major Ordos: Ordo Xenos (Aliens), Ordo Hereticus (Heretics), and Ordo Malleus (Daemons).",
  "An Inquisitorial Retinue is a mixed, specialized force of assassins, soldiers, and specialists that serve a single Inquisitor.",
  "The Ordo Malleus is the least public of the Ordos, secretly dedicated to hunting and destroying the terrifying forces of Chaos Daemons.",
  "The Ordo Xenos is responsible for identifying, categorizing, and authorizing the extermination of all alien threats to humanity.",
  "The Ordo Hereticus roots out internal threats, including rogue psykers, dangerous mutants, and traitors within the Imperium's own institutions.",
  "The Witch Hunters are agents of the Ordo Hereticus who specialize in identifying and eliminating unsanctioned psykers.",
  "A Radical Inquisitor is one who believes in using the enemy's own weapons and methods against them, often walking dangerously close to heresy themselves.",
  "A Puritan Inquisitor believes that the only safe method is to ruthlessly exterminate any threat with the utmost orthodoxy.",
  "Interrogators are the junior agents of the Inquisition, undertaking dangerous assignments to prove their worth to their Inquisitor Lord.",
  "The Raptor is an Inquisitor's primary personal transport, a small, heavily armed craft designed for rapid, anonymous deployment.",
  "Confessors are the most fanatic preachers of the Ecclesiarchy, often accompanying troops into battle to inspire them to suicidal fervor.",
  "Missionary organizations of the Ecclesiarchy venture into newly discovered or recovered worlds to establish the Imperial Creed.",
  "The Adeptus Sororitas are housed in specialized Convents, which serve as their training grounds and fortified strongholds.",
  "Repentia Squads are Sisters of Battle who seek atonement for real or perceived failings, charging into battle with massive, two-handed chainswords.",
  "The Dialogus Sisters specialize in linguistics and translation, serving as the official record-keepers and communicators for the Sororitas.",
  "The Hospitaliers are the Sisters of Battle who serve as field medics, often seen aiding wounded Guardsmen on the front lines.",
  "The Sanctuary is the sacred relic carried by the Sisters of Battle, often a fragment of a saint or a preserved piece of holy cloth.",
  "The Act of Faith is the innate ability of the Sisters of Battle to draw upon their absolute devotion to the Emperor to perform superhuman feats.",
  "The Temple of the Saviour Emperor is the colossal, ornate main cathedral and headquarters of the Ecclesiarchy on Terra.",
  "The Black Guard is the informal name for the highest-ranking, veteran Sisters of Battle who serve as the personal bodyguards of a Canoness.",
  "A Paragon Warsuit is a massive, heavily armored, powered suit worn by the most veteran Sisters Superior for heavy combat.",
  "Arco-flagellants are mindless, pain-driven creatures, once criminals, surgically and chemically augmented to be instruments of holy wrath.",
  "The Schola Progenium trains future Sisters, Commissars, and senior Administratum officials, instilling total loyalty from a young age.",
  "The Death World tax is a massive, mandatory levy of manpower and resources placed upon planets with exceptionally harsh environments.",
  "Stasis Chambers are often found on ancient vessels and deep-space research stations, keeping their occupants alive and unchanged for millennia.",
  "The Officio Assassinorum is the clandestine Imperial organization that houses and deploys the various temples of elite assassins.",
  "The Imperial Navy is the space-faring military force of the Imperium, separate from the Astra Militarum, responsible for all deep-space combat.",
  "The War Council of a Sub-sector is a meeting of all the highest-ranking military and political leaders to plan the defense against a major threat.",
  "The Seal of Purity is a wax seal affixed to a scroll inscribed with a holy text, used as both a ward and a mark of Imperial sanction.",
  "The Vox-caster is the standard, bulky radio communications equipment used by the Imperial Guard for long-range communication.",
  "Holy Terra is the spiritual heart of the Imperium, but it is so polluted and densely built that its original geography is lost.",
  "The Eye of Terror expanded violently after the Fall of Cadia, creating the Great Rift, which now divides the galaxy.",
  "Cadia was the most heavily fortified planet in the galaxy, guarding the only stable exit point from the Eye of Terror.",
  "The Gellar Field is a ship's essential device that projects a bubble of reality into the Warp, preventing Daemonic entities from boarding.",
  "Warp Storms are massive, unpredictable disturbances in the Immaterium that can instantly consume entire fleets or deposit them thousands of years in the future.",
  "The Age of Strife was the terrible period of galactic isolation and technological regression that followed the fall of the Golden Age.",
  "No Man's Land is the desolate, radioactive, or war-torn area between two opposing trench lines on countless Imperial battlefields.",
  "The Cicatrix Maledictum is the formal, Imperial name for the Great Rift, literally translating to the \"Wound of the Curse.\"",
  "Segmentum Solar is the central, highly defended administrative sector of the Imperium, containing Terra and Mars.",
  "The Halo Zone is the incredibly vast, unexplored, and dangerous galactic region far beyond the Imperium’s borders.",
  "Blackstone Fortresses are massive, self-aware space stations of unknown, probably xenos, origin, often converted by the Imperium or Chaos.",
  "Relics of Mars are the Mechanicus's most sacred technological artifacts, often housed in impregnable, climate-controlled vaults.",
  "The Cursed Founding refers to the experimental 21st Founding of Space Marine Chapters, which produced many Chapters with terrible genetic flaws.",
  "The Badab War was a massive internecine conflict between Space Marine Chapters that almost shattered a key sector of the Imperium.",
  "The Ghoul Stars is a dark region of space known for its hostile, unknown, and extremely violent xenos life forms.",
  "Sanctuary 101 is a pivotal location in the lore, where the Grey Knights engaged in a monumental battle with the forces of Chaos.",
  "The Ring of Iron is the massive, interlocking orbital defense network that protects the Segmentum Solar from attack.",
  "Daemonifuge is the name for a rare human who is genetically and psychically immune to Daemonic possession.",
  "The Pariah Gene is a rare, naturally occurring psychic \"blankness\" in humans that negates all Warp energy around them.",
  "Psyker Cages are specialized, insulated prisons used to transport and hold captured Psykers, preventing them from causing harm.",
  "Witchfire is the common term for psychic energy and spellcasting used by unsanctioned or Chaos-corrupted Psykers.",
  "The Emperor’s Tarot is a highly revered, complex divination tool used by high-ranking Imperial officials and Psykers.",
  "The Book of Lorgar is the most profane and heretical text in the galaxy, penned by the traitor Primarch, Lorgar Aurelian.",
  "Cataract of Hate is the name of a massive, long-running Warp Storm that makes travel impossible in a key part of the galaxy.",
  "Promethium is the Imperium's universal fuel, a crude oil derivative often burned for power and used in flamers.",
  "Archetypal Worlds include Forge Worlds, Hive Worlds, Death Worlds, Shrine Worlds, and Agripinaa Worlds (farms).",
  "Stygies VIII is a Forge World of the Mechanicus notorious for its obsession with studying and hoarding Xenos technology.",
  "The Ark Mechanicus is the term for the largest, most powerful starships of the Mechanicus, carrying entire industries and armies.",
  "The Hell Blade is a fast, agile, Daemon-possessed fighter jet used by the forces of Chaos.",
  "The Stormbird was a massive, ancient Space Marine atmospheric dropship, predating the more common Thunderhawk.",
  "Sable 17 is an infamous Penal Colony, a barren rock where the worst criminals in the Imperium are sent to slowly die.",
  "The Astronomer Royal is the Mechanicus official responsible for charting and maintaining the functionality of the Astronomican.",
  "The Silent King, the ultimate leader of the Necrons, returned to the galaxy after a long absence to unite his fragmented people against the Tyranids.",
  "The Long War is the term used by the Chaos Space Marines for the 10,000-year conflict against the Imperium since the Horus Heresy.",
  "The Red Path is the philosophical code of the Khorne Berzerkers, advocating for total, unrestrained bloodletting in all conflicts.",
  "The Great Devourer is the term the Imperium uses to refer to the Tyranid race as a whole, reflecting their terrifying, all-consuming nature.",
  "Infralights are specialized, red-spectrum lights used in Dark Eldar ships to minimize the ambient light and maximize terror.",
  "The Path of the Warrior is the path of life chosen by the Eldar Aspect Warriors, where they temporarily give over their personality to the war mask.",
  "The Codex Astartes includes detailed instructions on Chapter organization, combat doctrine, and even proper color schemes for vehicles.",
  "The Warp Gate is the colloquial term for a stable, permanent portal between the real world and the Immaterium.",
  "Agri-Worlds are worlds dedicated solely to food production, often suffering from catastrophic over-farming and environmental decay.",
  "Forgefiends are massive, four-legged Chaos Daemon Engines armed with powerful, multi-barreled cannons.",
  "The Corpse-Emperor is the derisive term used by Chaos followers to refer to the dying Emperor on the Golden Throne.",
  "The Ark of Lost Souls is a massive, derelict Eldar Craftworld, completely lifeless and haunted by the echoes of those slain by Slaanesh.",
  "The Doom of Malan'tai was a Tyranid bioform that psychically consumed the entire population of an Eldar Craftworld, gaining immense power.",
  "The Sabbat Worlds Crusade was a decades-long, bloody conflict to reclaim a specific region of space from the forces of Chaos.",
  "The Lord of Change is the powerful Greater Daemon of Tzeentch, a multi-eyed, winged horror capable of manipulating reality.",
  "Chaos Undivided refers to those Chaos forces who do not strictly worship one God, but pay homage to all four equally.",
  "The Screaming Vortex is a minor, yet powerful, Warp storm known for its unique, localized Chaos factions and daemonic entities.",
  "Psychic Null technology is rare and valued, used by the Sisters of Silence and some Inquisitorial retinues to counter enemy Psykers.",
  "Void Shields are energy fields that protect major Imperial facilities and ships by shunting incoming energy and matter into the Warp.",
  "Death Worlds are planets so dangerous that only the toughest life forms, or the most dedicated Imperial forces, can survive there.",
  "Axiom Imperatus is the set of unwritten, traditional beliefs and cultural norms that guide the Adeptus Administratum.",
  "The Hellfire Rounds of the Deathwatch are specialty bolt-shells containing a potent bio-acid, designed to destroy Tyranid bioforms.",
  "Phase Technology is a rare form of Necron technology that allows their units to briefly become immaterial, passing through solid objects.",
  "Glimpse of the Future is the Eldar Farseer's ability to briefly look into the Webway's psychic flow to determine likely future events.",
  "The Laughing God, Cegorach, is the only Eldar deity to have survived the Fall of the Eldar, now guiding the Harlequins.",
  "The Dark City of Commorragh exists within the Webway, constantly moving and avoiding detection by the forces of Slaanesh.",
  "The Webway is a massive, interdimensional labyrinth of tunnels built by the Old Ones, allowing the Eldar to travel across the galaxy safely.",
  "Tomb Kings of Khemri are referenced in ancient Mechanicus texts as another race of deathless, metal-clad warriors.",
  "Star Forts are gigantic, permanent Imperial space stations, serving as command centers, repair docks, and defensive bulwarks.",
  "The Emperor's Champion is a Black Templar selected by divine inspiration to carry a sacred sword and challenge the greatest enemy champion.",
  "The Eightbound are World Eaters possessing eight daemons in a single body.",
  "Corrupted Gene-Seed is the biggest fear of the Apothecaries, as it threatens the purity and future of their entire Chapter.",
  "Hobbyists are a faction of Dark Eldar Haemonculi who experiment on living flesh to create new forms of pain-beasts.",
  "Homunculi are the insane, twisted flesh-sculptors of the Dark Eldar, experts in torture, agony, and biological warfare.",
  "The Red Gobbo is a legendary, revolutionary Ork figure who believes Orks should fight for the small guy (Gretchin), not the big Bosses.",
  "The Green Tide is the colloquial term for a massive, unstoppable Ork WAAAGH! that washes over entire star systems.",
  "The Shas'O is the highest military rank available to a Fire Caste T'au commander.",
  "Markerlights are the T'au's most crucial targeting aids, used to designate enemy targets and increase the accuracy of all subsequent T'au fire.",
  "The Khrave are mind-eating xenos that plagued the galaxy during the Great Crusade, requiring the Lion to exterminate them.",
  "The Lords of Silence are a prominent Warband of the Death Guard known for their tactical patience.",
  "Malice is a possible fifth Chaos God, briefly mentioned as a deity of anarchy and self-destruction, but rarely acknowledged.",
  "The Enslaver Plague was a major psychic catastrophe during the Age of Strife, where the xenos entities known as Enslavers took over entire populations.",
  "The Unnamed War is the term for the galactic conflict between the Old Ones and the C'tan/Necrons that set the stage for all subsequent history.",
  "The Great Blackout was a period of galactic darkness that accompanied the birth of the Great Rift, where the Astronomican was temporarily obscured.",
  "The Astronomican's failure is a constant, underlying fear for all Imperial citizens, as it would mean the total cessation of Warp travel.",
  "Relic Contamination is the Inquisitorial concern that ancient technology may be harboring heretical code or xenos influence.",
  "The Helmawr Line is the ancient, powerful noble dynasty that controls the infamous Hive World of Necromunda.",
  "Amasec is the highly potent, often terrible-tasting alcoholic drink consumed throughout the Imperium.",
  "The Schola Psykana is the Imperial institution on Terra responsible for training and sanctioning Astropaths and Psykers.",
  "The Flesh-change was a psychic mutation that ravaged the Thousand Sons Legion before the Rubric, turning many into monstrous abominations.",
  "The Iron Halo is a personal force-field generator worn by Space Marine Captains and Chaplains, projecting a defensive shield.",
  "The Thunderhawk Gunship is the Space Marines' primary dropship and heavy attack aircraft, capable of atmospheric and void combat.",
  "Warp Drives use large, specialized engines to create the initial void in reality required to enter the Immaterium.",
  "Psychic Hoods are specialized helmet attachments worn by Imperial Psykers to amplify and focus their powers, while guarding against Daemonic influence.",
  "The Great Purge was the Imperial action that followed the Horus Heresy, where loyalist forces hunted down and destroyed Chaos remnants.",
  "The Crimson Slaughter is a Chaos warband of unknown origin, driven mad by the incessant screams of their own dead.",
  "The C'tan Shards are fragments of the once-godlike Star Gods, now bound into Necron vehicles and weaponry to serve their masters.",
  "Trazyn the Infinite is a notorious Necron Overlord who collects entire populations, buildings, and battlefields, storing them in vast stasis museums.",
  "The Tomb World of Somonor is rumored to contain a working, intact STC blueprint for a powerful new weapon.",
  "The Shadow Captain is the equivalent of a Company Captain in the Raven Guard, specializing in stealth and guerrilla tactics. ",
  "Black Rage victims often see themselves as the Primarch Sanguinius in his final battle against Horus.",
  "The Blood Tithe is the sacrificial killing demanded by the followers of Khorne to appease their violent deity.",
  "The Lord of Skulls is the massive, tracked, heavily armed Chaos Daemon Engine dedicated entirely to Khorne's bloody glory.",
  "The Tallyman is a specialized Death Guard warrior who zealously counts casualties and blights to invoke Nurgle's favor.",
  "The Masque is the term for a traveling troupe of Eldar Harlequins, whose performance often culminates in real-space warfare.",
  "The Path of the Outcast is the dangerous, self-destructive path of an Eldar who fails to master the chosen \"Path\" of their society.",
  "The Grotesques are the hulking, bio-engineered servants of the Dark Eldar Haemonculi, created from the tormented flesh of their captives.",
  "The Scourges are winged Dark Eldar warriors, equipped with powerful energy weapons and highly mobile jump packs.",
  "Tau Drones are ubiquitous robotic assets, serving as mobile shields, weapon platforms, or dedicated field repair systems.",
  "The Vespid Crystal is a unique energy source used by the Vespid Stingwings, which powers their potent ion weaponry.",
  "The Tyrant Guard are massive, heavily armored Tyranid bodyguards, instinctively sacrificing themselves to protect their Hive Tyrant leader.",
  "The Termagants are the basic, fast-moving cannon fodder of the Tyranid swarm, armed with bio-engineered flesh-weapons.",
  "The Exocrine is a massive Tyranid artillery organism, capable of launching powerful salvos of high-explosive bio-projectiles.",
  "The Void Dragon is a C'tan Shard rumored to be imprisoned beneath the surface of Mars, influencing the Machine God's worship.",
  "The Phosphex is a terrifying, ancient, self-igniting chemical weapon used primarily by the Iron Warriors during the Heresy.",
  "The War Boss is the title for the most powerful, battle-crazed Ork commander in a specific region of a WAAAGH!",
  "The Imperial Truth was the Emperor's original, atheistic decree during the Great Crusade, stating that there were no gods, only science and logic.",
  "The Adeptus Administratum has entire sectors of its organization dedicated solely to the documentation and cataloging of other documentation.",
  "The Relic Malice is a heretical Chaos artifact that drives any who touch it into a state of uncontrollable, violent paranoia.",
  "Fulgrim, Primarch of the Emperor's Children, personally slew his brother Ferrus Manus and offered his head to Slaanesh.",
  "The Planet Eater is a term for a massive, ancient Necron weapon capable of destroying entire planetary cores.",
  "Sanctioned Psykers of the Imperium are often fitted with specialized, ornate headwear to help contain and focus their Warp powers.",
  "The Shrine Worlds are planets dedicated entirely to the worship of the Emperor or a specific Imperial Saint, often attracting pilgrims.",
  "A Rogue Trader's power is theoretically absolute within the bounds of their charter, making them minor, private warlords.",
  "The Great Slaughter is the eventual destiny of those who worship Khorne, who will inevitably turn their blades on each other.",
  "The Gellar Field must be disengaged for a ship to drop out of the Warp, making this moment terrifyingly vulnerable.",
  "The Eightbound are World Eaters possessing eight daemons in a single body.",
  "The Dolmen Gates are Necron devices used to breach the Webway, bypassing the need for Warp travel.",
  "The Administratum processes millions of logistical requests per second, of which only a tiny fraction are ever correctly actioned.",
  "The Planet of the Sorcerers contains the fortress-pyramid of the Thousand Sons, constantly shifting and defying reality.",
  "The Space Wolves' home world, Fenris, is a highly volatile death world of extreme seismic and volcanic activity.",
  "Terra's surface is coated in centuries of human debris, with the original continents now buried miles deep.",
  "The Golden Throne's daily power drain is so immense that any disruption could plunge the entire Segmentum Solar into darkness.",
  "The Vindicare Assassin's primary weapon is the Exitus Rifle, a silent, high-caliber sniper rifle firing armor-piercing rounds.",
  "The Callidus Assassin's transformation is so total that even medical scans cannot distinguish her from the person she is impersonating.",
  "The Eversor Assassin is usually deployed only when total, widespread elimination of an enemy command structure is necessary.",
  "The Cult of the Machine God is a pragmatic belief system that views technology as an ultimate, divine force.",
  "The Skitarii Rangers are specialized, long-range patrol troops of the Mechanicus, capable of traversing vast, toxic wastelands.",
  "The Adeptus Custodes are rumored to possess gene-seed, but their unique creation process is far more complex than that of a Space Marine.",
  "The Blood Angels' homeworld, Baal, is a radioactive, barely habitable ruin, constantly threatened by Tyranid fleets.",
  "The Ultramarines are the founders of the Five Hundred Worlds of Ultramar, an internally stable and prosperous mini-Imperium.",
  "The Black Legion was originally known as the Luna Wolves, then the Sons of Horus, before adopting their current black livery in shame.",
  "The Iron Cage battle was so devastating that it is believed to have driven the Imperial Fist Primarch, Rogal Dorn, to the brink of madness.",
  "The Lords of Silence are a prominent Warband of the Death Guard known for their tactical patience.",
  "The Nexus Arrangement is a Necron device capable of silencing the Warp across a massive area.",
  "The Imperium's calendar is so convoluted and inaccurate that entire sectors often disagree on what year it currently is.",
  "The Dark Eldar are constantly raided by their own kind, as internal strife and betrayal are their culture's core tenets.",
  "The Necrons can summon devastating orbital bombardment simply by telepathically commanding their ships from the surface of a Tomb World.",
  "The Ork's culture is so ingrained in fighting that even during peacetime, they fight among themselves to stay in practice.",
  "The Great Rift's expansion created Imperium Nihilus, the half of the galaxy cut off from the light of the Astronomican.",
  "The Lord Commander of the Imperium, Roboute Guilliman, is one of the only Primarchs still actively leading Imperial forces.",
  "The Keys of Hel are forbidden technologies used by the Iron Hands to resurrect the dead as cybernetic horrors.",
  "Chaos Spawns are the ultimate warning to the followers of the Chaos Gods: failure to please results in physical dissolution.",
  "The Great Game is the eternal, destructive rivalry between the four Chaos Gods, whose shifting alliances and backstabbing affect all reality.",
  "The Astropathic Choir is constantly replenished with new, terrified recruits from the Black Ships.",
  "The Golden Throne is not merely a life-support device, but also the lynchpin of the Emperor's psychic defense against a massive Warp breach on Terra.",
  "Despite the endless war, the Imperium is so vast that billions of citizens live and die without ever seeing a Space Marine or firing a lasgun in battle."
}
return LORE
